### ISSUE TITLE
No Postgres Files

### ISSUE THREAD

**Issue by jollyrogue** [michaljuhas/sample-database#2]
README.md references `/PostgreSQL/`, but it doesn't exist.

**Comment by michaljuhas** [comment]
Good spot, at first I wanted to do Postgres, too, but then focused on MySQL only. Will drop the reference now, thanks!

**Comment by MatMoore** [comment]
Hi @michaljuhas

I noticed this is also referenced in the "S01-L06 Checklist before jumping on section S02" video on the Udemy course as well (it suggests importing the sample data for both MySQL and Posgres).
